### PR TITLE
Windows fixes

### PR DESCRIPTION
**Pull request by mikavilpas**
Continuing the work started in #73. Got stalled because of build system issues 🤷🏻‍♂️

### CODE REVIEW

**Comment by Kayzels** [comment]
Doesn't this last commit break the changes for mikavilpas/yazi.nvim@051bfce, though? I will test it soon.

**Comment by Kayzels** [comment]
So, I'll need to test it now. From what I can tell, you removed the quotes around the input file for Yazi? With that, now the spaces will need to be escaped, so my earlier commit probably won't work. I'll see if there's a way to get it working.

**Comment by Kayzels** [comment]
There isn't an easy way to escape spaces in Powershell, so this removal of the quotes is a breaking change. Is there no way to keep them in while still working on Mac? Unfortunately, the tests aren't system agnostic, so changes to make it work for Windows will cause some tests to fail, from what I can see.

**Comment by mikavilpas** [comment]
Hmm, I think it's possible to keep them on Windows specifically. I pushed a change to hopefully fix this for you.

The testing setup doesn't work at all on windows right now 😅 

Can you try the latest version out?

**Pull request merged**
